twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        trick_images_dir: 'public/uploads/tricks/'

when@test:
    twig:
        strict_variables: true
